### ISSUE TITLE
negative time, restore_neutron/xray and GROUP

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#134]
**Reported by erkn on 14 Jun 2012 11:01 UTC**
There is a problem when having a monitor (or monitors) behind the particle. If it is not set in a group it will be absorbed no matter if the restore_neutron/xray flag is set. If in a group there will an error message is issued but the particle is propagated and tested as it should.

When the restore flag is set, the particle should not be terminated and in any case the error message should not be issued when in a group.

**Comment by willend** [comment]
**Comment by erkn on 14 Jun 2012 11:03 UTC**
A solution for the first issue is to ensure that monitors have a construction like:

if(!restore_neutron){
  PROP_DT(t);
else{
  ALLOW_BACKPROP;
  PROP_DT(t);
}
and similar for xrays.

**Comment by willend** [comment]
**Modified by erkn on 26 Feb 2013 17:03 UTC**

**Comment by willend** [comment]
**Comment by erkn on 7 Jun 2013 08:47 UTC**
The above solution is not safe - this would allow particles to go back in time and also hit the monitor, which is probably not desired

**Comment by willend** [comment]
**Comment by farhi on 18 Jun 2014 13:28 UTC**
has been fixed for 2.1 by allowing back prop by default in propagation.

**Comment by MilanKlausz** [comment]
I'd like to point out that the second part of the issue is still not solved. The error message:

> (negative time, miss next components, rounding errors, Nan, Inf)

 is still issued if there is a component(monitor) in a GROUP that is 'behind' the particle. This can easily happen for example when using an NCrystal_sample component (that doesn't focus the outgoing particles on a component) and monitoring both the transmitted and the scattered neutrons. The particles are propagated properly but the error message is quite misleading.
