### ISSUE TITLE
mc(x)doc "next generation" for McStas 2.5

### ISSUE THREAD

**Issue by willend** [McStasMcXtrace/McCode#571]
Tasks:
- @ebknudsen and @willend should evaluate the (partial?) implementation and comment / formulate another issue
- @climbcat should then implement based on that input

**Comment by willend** [comment]
From https://github.com/McStasMcXtrace/McCode/issues/427: (which I will now close)

Existing perl implementation

Run at install time for generating comp and instr .html pages in MCSTAS/sources etc.
Run at user simulation time for generating overview doc page with table including comp, instr info etc.
-- Command: mcdoc
-- Optional input args:
--- "PSD" -> matches PSDinstr and PSDcomp
--- directory/
--- -m gives PDF manual
--- -c gives component PDF manual
--- further hidden thingies...
-- --test runs the "test suite", or --test PSI_DMC runs test for PSI_DMC !!NB!! Should be independent tool on the python side. mctest?? - see separate issue
-- If no input arg is given, MCSTAS version directory with subfolders sources, samples, ... (hardcoded list) + current dir is traversed
Above catalogue is determined automatically unless filename/dirname input given
Output data: mcdoc_Xysz0023dq2.html with links to relevant comp/instr html pages (filtered by the above PSD

**Comment by willend** [comment]
@climbcat I've had a first look, and it seems mostly good! The table of components and instruments is nice and the links are functional.

The top links to, local, data and share currently point to nothing, see attached:

I suggest to
1) add . to the search and put these in 'local'
2) make data a simple link to file:///whereever/mcstas/is/installed/data
3) make share a simple link to file:///whereever/mcstas/is/installed/share

I will now proceed to package under #683 which will make testing easier

**Comment by willend** [comment]
We will also need command line switches to access the manuals, that is

<pre>
mcdoc -m
mcdoc -c
</pre>

Searching for e.g. source-oriented comps seems to work OK

**Comment by willend** [comment]
Interchange Name and Unit columns in generated html

**Comment by willend** [comment]
Hi @climbcat,
Looks good with the latest modifications to mcdoc(py)!

It occurs to me that maybe the order of Name / Unit is still not right in the table? See attached which I just generated using mcdoc from the repo 

<img width="890" alt="screenshot 2018-11-29 at 20 36 35" src="https://user-images.githubusercontent.com/8593355/49246996-7ab5e900-f416-11e8-9435-bc574d0b3024.png">

**Comment by willend** [comment]
Oh and one more detail! :-) In the above graphic from a component - the title includes "Instrument". Better fix that one ;-)

**Comment by willend** [comment]
From the attached graphic and instrument it also seems that the basic variable type is used as "unit" instead of the physical unit from the Parameter lines?
![screenshot 2018-11-30 at 11 14 29](https://user-images.githubusercontent.com/8593355/49283107-23089380-f491-11e8-93ba-8ab185cc3e89.png)
[ISIS_TOSCA_preupgrade_Mantid.instr.txt](https://github.com/McStasMcXtrace/McCode/files/2632833/ISIS_TOSCA_preupgrade_Mantid.instr.txt)

**Comment by climbcat** [comment]
Most of the stuff should have been fixed by this: 69442b044aa8bdccde029f78d07ff0b76b6746a6

**Comment by climbcat** [comment]
The units seem to be not read correctly from file. In some cases, it can't be done, but after the docs parsing job a few months back, in most cases it can. I'll have to look into this.

**Comment by climbcat** [comment]
A few bugs and shortcomings have been fixed, and I dare claim that mcdoc-py is now better than ever, ready for another round of test/review.

**Comment by willend** [comment]
OK, received - will try to test tonight / tomorrow

**Comment by willend** [comment]
Hi there,

Agreed - much better. I have tested and found three remaining minor issues:

1) The component pages still get a header that says "Instrument"

2) It would be nice to have bold font face on the headers in the tabular columns

3) For some reason e.g. Source Maxwell 3 (and other comps in the list also) gets an empty first line in the parameters:
<img width="893" alt="screenshot 2018-12-03 at 19 38 39" src="https://user-images.githubusercontent.com/8593355/49394299-ce387780-f733-11e8-89a6-7125546fe1e2.png">

- which is not there in the output from the Perl version:

<img width="981" alt="screenshot 2018-12-03 at 19 38 29" src="https://user-images.githubusercontent.com/8593355/49394378-fc1dbc00-f733-11e8-81ba-b41b5752ef96.png">

**Comment by willend** [comment]
Component pages now has header that says "Component" and the parameter headers are in bold.

Also added -w -m -c switches for website, manual and component manual.

Missing is stil:
* The empty rows that some components give
* Why don't we get lambda0 in Source_maxwell3 ?
* We write that optional parameters are in bold (those with default value 0) - which they are currently not

**Comment by climbcat** [comment]
This should have been implemented with 0bc45a38f4d005efc3b133576d21810f454bf885 and 9883a2cff722cb53c5904e9464abbbf70779ce3f

**Comment by willend** [comment]
Looks good, declared DONE
